#
# Docker based environment.
#
---

version: '3.7'

networks:
  docker-network:
    name: docker-network
    driver: bridge

services:
  mysql:
    container_name: 'mysql'
    hostname: 'db'
    image: mysql/mysql-server:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/provision:/var/provision
      - ./docker/mysql/storage/mysql:/var/lib/mysql
      - ./docker/mysql/storage/backups:/var/backups
    ports:
      - 9360:3306
    networks:
      - 'docker-network'
